services:
  web:
    image: coldshort/todb18_cuoikhoa_yeucau1_nginxwelcome:latest
    ports:
     - "${PORT:-8080}:80"
    environment:
      NAME: "${NAME:-someone}"
    command: >
      /bin/sh -c
      "envsubst < /usr/share/nginx/html/index.template.html
      > /usr/share/nginx/html/index.html
      && nginx -g 'daemon off;'"
